### ISSUE TITLE
Add User.isValid method

### ISSUE THREAD

**Issue by dzmitrykashlach** [Blazemeter/blazemeter-api-client#73]
Used in JEN/BAM.

**Comment by artem-fedorov** [comment]
I use `User.getUser()` for validate in TC plugin

**Comment by dzmitrykashlach** [comment]
Me too. Just propose to wrap it into try/catch and extract in separate method.

**Comment by artem-fedorov** [comment]
I think it is better to have exception with error message from server, that just `false`

**Comment by dzmitrykashlach** [comment]
ok
