### ISSUE TITLE
TestListFlow - getAllTestsForWorkspace(Workspace workspace)

### ISSUE THREAD

**Issue by dzmitrykashlach** [Blazemeter/blazemeter-api-client#74]
used in JEN plugin.

**Comment by artem-fedorov** [comment]
We have getSingleTestsForWorkspace and getMultiTestsForWorkspace 
I think it's the same. We should make all private methods in ciworkslow package protected

**Comment by dzmitrykashlach** [comment]
Yes, I know. Just wanted to combine getSingleTestsForWorkspace/getMultiTestsForWorkspace into public wrapper-method. But not urgent, because I use this only in JEN plugin.
